### ISSUE TITLE
week.number.pos ?????

### ISSUE THREAD

**Issue by demorsick** [R-CoderDotCom/calendR#18]
is there anyway to center the numbers of the week?

**Comment by mschilli87** [comment]
@demorsick: Can you elaborate what exactly you are trying to achieve? Ideally, you'd provide a minimal example code with the output you get and a mockup of what you would like to get (for example by editing the current output manually).

**Comment by demorsick** [comment]
[calendR.pdf](https://github.com/R-CoderDotCom/calendR/files/9792403/calendR.pdf)
here's a small example that i made using tikz

**Comment by mschilli87** [comment]
The reason the day numbers are in the corner is because you can add additional text for the days in the month view (see the [README](https://github.com/R-CoderDotCom/calendR#monthly-calendar)):

> ```r
> calendR(year = 2028, month = 1)
> ```

![month](https://user-images.githubusercontent.com/12913701/196043711-6104c206-1d91-48c7-9f0a-6823aeaf1a57.png)

> ```r
> calendR(month = 7, year = 2022, 
>         special.days = c(1, 5, 12, 28),       # Color days of the month
>         text = "Visit\nhttps://r-coder.com/", # Add some text
>         text.pos = c(1, 5, 12, 28))           # Where to add the text
> ```

![month_with_text](https://user-images.githubusercontent.com/12913701/196043785-340b0039-a25c-4560-a8fd-b74395242864.png)

You could use that to simply repeat the days:

```r
calendR(month = 2, year = 2023, 
        text = 1:28,     # Requires the correct number of...
        text.pos = 1:28) # ... days for the given month!
```

![month_with_days_twice](https://user-images.githubusercontent.com/12913701/196044000-c4d14db9-6752-42b8-bddc-c96dfc82005b.png)

Finally, to hide the 'original' day numbers in the corner, you can set their size to zero:

```r
calendR(month = 2, year = 2023, 
        text = 1:28, text.pos = 1:28,
        day.size = 0)
```

![month_with_days_centered](https://user-images.githubusercontent.com/12913701/196044092-8dc53232-5d76-4a34-8a1c-69399aff187b.png)

I hope this solves your problem. You could wrap this in a nice little function that automatically determines the correct number of days in the given month but I'll leave that as an exercise for you. :wink:

**Comment by demorsick** [comment]
thanks
